apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../platform/sources
  - ../../platform/traefik
  - ../../platform/cache
  - ../../platform/databases
  - ../../platform/messaging
  - ../../platform/observability
  - ../../platform/secrets
  - ../../apps
